package my.tipcalculator.ui.theme

import androidx.compose.ui.graphics.Color

val sofia_theme_light_primary = Color(0xFF914277)
val sofia_theme_light_onPrimary = Color(0xFFFFFFFF)
val sofia_theme_light_primaryContainer = Color(0xFFFFD8EC)
val sofia_theme_light_primaryVariant = Color(0xFF3B002D)
val sofia_theme_light_secondary = Color(0xFF715765)
val sofia_theme_light_onSecondary = Color(0xFFFFFFFF)
val sofia_theme_light_secondaryContainer = Color(0xFFFBD9EA)
val sofia_theme_light_secondaryVariant = Color(0xFF291521)
//val sofia_theme_light_tertiary = Color(0xFF80543D)
//val sofia_theme_light_onTertiary = Color(0xFFFFFFFF)
//val sofia_theme_light_tertiaryContainer = Color(0xFFFFDBCB)
//val sofia_theme_light_onTertiaryContainer = Color(0xFF311303)
val sofia_theme_light_error = Color(0xFFBA1A1A)
//val sofia_theme_light_errorContainer = Color(0xFFFFDAD6)
val sofia_theme_light_onError = Color(0xFFFFFFFF)
//val sofia_theme_light_onErrorContainer = Color(0xFF410002)
val sofia_theme_light_background = Color(0xFFFFFBFF)
val sofia_theme_light_onBackground = Color(0xFF1F1A1C)
val sofia_theme_light_outline = Color(0xFF81737A)
val sofia_theme_light_inverseOnSurface = Color(0xFFF9EEF1)
val sofia_theme_light_inverseSurface = Color(0xFF342F31)
val sofia_theme_light_inversePrimary = Color(0xFFFFAEDE)
val sofia_theme_light_surfaceTint = Color(0xFF914277)
val sofia_theme_light_outlineVariant = Color(0xFFD3C2C9)
val sofia_theme_light_scrim = Color(0xFF000000)
val sofia_theme_light_surface = Color(0xFFFFF8F9)
val sofia_theme_light_onSurface = Color(0xFF1F1A1C)
val sofia_theme_light_surfaceVariant = Color(0xFFF0DEE5)
val sofia_theme_light_onSurfaceVariant = Color(0xFF4F4449)

val sofia_theme_dark_primary = Color(0xFFFFAEDE)
val sofia_theme_dark_onPrimary = Color(0xFF591146)
val sofia_theme_dark_primaryContainer = Color(0xFF752A5E)
val sofia_theme_dark_primaryVariant = Color(0xFFFFD8EC)
val sofia_theme_dark_secondary = Color(0xFFDEBECE)
val sofia_theme_dark_onSecondary = Color(0xFF3F2A36)
val sofia_theme_dark_secondaryContainer = Color(0xFF57404D)
val sofia_theme_dark_secondaryVariant = Color(0xFFFBD9EA)
//val sofia_theme_dark_tertiary = Color(0xFFF4BA9E)
//val sofia_theme_dark_onTertiary = Color(0xFF4B2714)
//val sofia_theme_dark_tertiaryContainer = Color(0xFF653D28)
//val sofia_theme_dark_onTertiaryContainer = Color(0xFFFFDBCB)
val sofia_theme_dark_error = Color(0xFFFFB4AB)
val sofia_theme_dark_errorContainer = Color(0xFF93000A)
val sofia_theme_dark_onError = Color(0xFF690005)
val sofia_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val sofia_theme_dark_background = Color(0xFF1F1A1C)
val sofia_theme_dark_onBackground = Color(0xFFEAE0E3)
val sofia_theme_dark_outline = Color(0xFF9C8D93)
val sofia_theme_dark_inverseOnSurface = Color(0xFF1F1A1C)
val sofia_theme_dark_inverseSurface = Color(0xFFEAE0E3)
val sofia_theme_dark_inversePrimary = Color(0xFF914277)
val sofia_theme_dark_surfaceTint = Color(0xFFFFAEDE)
val sofia_theme_dark_outlineVariant = Color(0xFF4F4449)
val sofia_theme_dark_scrim = Color(0xFF000000)
val sofia_theme_dark_surface = Color(0xFF171214)
val sofia_theme_dark_onSurface = Color(0xFFCEC4C7)
val sofia_theme_dark_surfaceVariant = Color(0xFF4F4449)
val sofia_theme_dark_onSurfaceVariant = Color(0xFFD3C2C9)

//val seed = Color(0xFFFFAEDE)